# Generated by Django 5.0.4 on 2024-04-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_task_created_at_task_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
