# Generated by Django 5.0.4 on 2024-04-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_task_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='is_completed',
        ),
    ]
